def showMenu():
    print("")
    print("")
    print(" The Callevo ETL application accepts up to three arguments separated by spaces.")
    print(" The first argument is the action:")
    print("")
    print(" r       Date range; must include two arguments: the start date and the end date.")
    print(" d       Process will run for a single day; a second argument is expected.")
    print(" s       Process the entire month to generate the summary; must include two arguments: the start date and the end date.")
    print(" h       Displays help")
    print("")
    print(" The app will process data on a daily basis and generate statistics.")
    print("")
    print(" Examples:")
    print(" python main.py r 2026-04-01 2026-04-26")
    print(" python main.py d 2026-04-14")
    print(" python main.py s 2026-01-01 2026-04-30")
    print(" python main.py h")
    print("")
    print("")